[package]
name = "ctru-rt"
version = "0.1.0"
authors = ["Philipp Joram <mail@phijor.me>"]
edition = "2018"
links = "ctru-rt"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
r0 = "1"
linked_list_allocator = { version = "0.8", optional = true }
volatile = "0.2"
log = { version = "0.4", default-features = false }

[features]
default = [
    "heap",
]
heap = ["linked_list_allocator"]
