[package]
name = "ctru-rt"
version = "0.1.0"
authors = ["Philipp Joram <mail@phijor.me>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
r0 = "0.2"
linked_list_allocator = { version = "0.6", optional = true }
volatile = "0.2"

[features]
default = [
    "heap"
]
heap = ["linked_list_allocator"]
