[env]
XTARGET = "armv6k-nintendo-horizon_ctr-elf"
XBUILD_FLAGS = "-Zbuild-std=core,alloc"

[tasks.test]
disabled = true

[tasks.build]
command = "cargo"
args = ["build", "${XBUILD_FLAGS}", "${@}"]

[tasks.build-examples]
command = "cargo"
args = ["build", "${XBUILD_FLAGS}", "--examples", "${@}"]

[tasks.examples]
dependencies = ["build-examples"]
command = "3dsxtool"
args = [
	"target/${XTARGET}/debug/examples/hello_world.elf",
	"target/${XTARGET}/debug/examples/hello_world.3dsx",
]

[tasks.default]
dependencies = ["examples"]
