[env]
XTARGET = "armv6k-nintendo-horizon_ctr-elf"

[tasks.test]
disabled = true

[tasks.build]
command = "cargo"
args = ["xbuild", "--target", "${XTARGET}.json", "${@}"]

[tasks.build-examples]
command = "cargo"
args = ["xbuild", "--target", "${XTARGET}.json", "--examples", "${@}"]

[tasks.examples]
dependencies = ["build-examples"]
command = "3dsxtool"
args = [
	"target/${XTARGET}/debug/examples/hello_world.elf",
	"target/${XTARGET}/debug/examples/hello_world.3dsx",
]

[tasks.default]
dependencies = ["examples"]
