[tasks.test]
disabled = true

[tasks.build]
command = "cargo"
args = ["xbuild", "--target", "armv6k-nintendo-horizon_ctr-elf.json", "${@}"]

[tasks.build-examples]
command = "cargo"
args = ["xbuild", "--target", "armv6k-nintendo-horizon_ctr-elf.json", "--examples", "${@}"]

[tasks.examples]
dependencies = ["build-examples"]
command = "3dsxtool"
args = [
	"target/armv6k-nintendo-horizon_ctr-elf/debug/examples/hello_world.elf",
	"target/armv6k-nintendo-horizon_ctr-elf/debug/examples/hello_world.3dsx",
]

[tasks.default]
dependencies = ["examples"]
